### ISSUE TITLE
QTypeNumericalRecitUtils class name

### ISSUE THREAD

**Issue by mudrd8mz** [SN-RECIT-formation-a-distance/moodle-qtype_numericalrecit#1]
Strictly speaking, the class `QTypeNumericalRecitUtils` violates the naming rules - https://docs.moodle.org/dev/Plugin_contribution_checklist#Namespace_collisions

I don't think it's a blocker though as it is still unique enough. However, both the name and the camel case style feels very un-moodley.

**Comment by emilevirus** [comment]
Fixed with commit f2483816b54c689065bebc24f371b45a37ced693
