### ISSUE TITLE
Documentation page timeout

### ISSUE THREAD

**Issue by mudrd8mz** [SN-RECIT-formation-a-distance/moodle-qtype_numericalrecit#2]
The documentation button links to https://recitfad.ca/moodledocs/question-formule-demarche-recit.html 

That page does not load for me though.

**Comment by gustavobazzo** [comment]
Fixed with commit [43c2f21](https://github.com/SN-RECIT-formation-a-distance/moodle-qtype_numericalrecit/commit/43c2f21e2e9b5a097e38fd92c56fd6d5fed5b968)
