### ISSUE TITLE
Please clarify the BSD license mentioned in answer_unit.php

### ISSUE THREAD

**Issue by mudrd8mz** [SN-RECIT-formation-a-distance/moodle-qtype_numericalrecit#4]
https://github.com/SN-RECIT-formation-a-distance/moodle-qtype_numericalrecit/blob/3286c6617f2aa29c8e154867fbed60628b253520/src/answer_unit.php#L22

Ref: https://docs.moodle.org/dev/Plugin_contribution_checklist#Licensing

**Comment by gustavobazzo** [comment]
Fix with commit [6abe7f3](https://github.com/SN-RECIT-formation-a-distance/moodle-qtype_numericalrecit/commit/6abe7f3c5fe320dc429d0c3703cc5849b7cebc5e)
